export const SAVE_POSITION_DATA = "SAVE_POSITION_DATA";
export const SAVE_MAJOR = "SAVE_MAJOR";
export const SAVE_COLLEGES = "SAVE_COLLEGES";
export const SAVE_COMPANYS = "SAVE_COMPANYS";
export const SAVE_LANGUAGE = "SAVE_LANGUAGE"